project:
  name: "RepoSeed"
  oneLiner: "Create your next open source repository with batteries included"
  state: "beta"
  image: "https://github.com/okkur/reposeed/blob/master/media/logo.svg"
  website: ""
  description: |
    Start with the base layer necessary to focus on your project and not on the repository.  
    Licensing, structure, documentation and more boilerplate to get you started from your first commit.
  version: "v0.1.0"

vision:
  type: "community" # personal is the default.
  overview: |
    Providing a generic base layer for new open source repositories.
  items:
    - "Default usage on first initialization"
    - "Generic seed/base layer files"
    - "Additions to reposeed only accepted for generic usage"
    - "Specific additions should be added to the files after generation"
  concept: "Reposeed's core concept is to provide a basic selection of useful templates. With the help of a configuration file and a small substitution engine the project generates a seed layer for new open source repositories."
  aim: "Our aim is to provide a sufficient base to built a new open source project on top of. Reducing the burden for maintainers and decreasing the hurdles to get started."

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed/labels/starter%20issue"

supportLinks:
  documentation: "/docs"

readme:
  usageExample: |
    ```
    go get -v -u github.com/okkur/reposeed/cmd/reposeed/...
    mkdir YOUR-PROJECT
    ```  
    Run the following command to create the sample .seed-config.yaml file.
    ```
    reposeed init YOUR-PROJECT
    ```
    Change .seed-config.yaml to your needs.
    ```
    reposeed --conf=YOUR-PROJECT/.seed-config.yaml --output=YOUR-PROJECT
    ```

docs:
  development: |
    Run the following commands to install reposeed and change your directory to reposeed's source code directory.
    ```
    go get -v -u github.com/okkur/reposeed/cmd/reposeed/...
    cd $GOPATH/src/github.com/okkur/reposeed
    ```
    Then run following command to install **packr**
    ```
    make packr
    ```
    Then in case you made any changes on  templates, just run ```make``` or ```packr install ./cmd/reposeed``` to bundle templates in the generated binary.

emails:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  owner: "The RepoSeed authors"
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/okkur/reposeed"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-beta-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/okkur/reposeed.svg"
    link: "https://github.com/okkur/reposeed/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/okkur/reposeed.svg"
    link: "LICENSE"
    alt: "license"
