project:
  name: "Example Project" # required
  state: "unstable" # unstable, beta, stable are supported
  image: "/blob/master/logo.svg"
  website: "example.com"
  oneLiner: "Creating awesome things, while enjoying live."
  description: |
    Free software developers guarantee everyone equal rights to their programs;
    any user can study the source code, modify it, and share the program.
    By contrast, most software carries fine print that denies users these basic rights, leaving them susceptible to the whims of its owners.
  # required
  version: "v0.0.0"
  mainLicense: "apache2" # default: apache2
    # Creative Commons: CCBy CCSa CCBySa CCByNcSa CC0
    # GPL: GPLv3 AGPLv3
    # Other: Apache2 MIT
  docsLicense: "CCBySa" # default: CCBySa
    # Creative Commons: CCBy CCSa CCBySa CCByNcSa CC0

vision:
  type: "personal" # personal is the default.
  overview: |
    This project thrives to be open, transparent and helpful.
  # required
  items:
    - "Only specific categories allowed"
    - "Bugfixes only"
    - "For personal projects only"
  concept: "Example Project's core concept to showcase how, why it does what it does."
  aim: "Example Project should only provide a small core and further additions should be done in helper projects/plugins or some sort."

supportPlatforms:
  - service: "Chat"
    link: "chat.example.com"
  - service: "User Mailinglist"
    link: "list.example.com"
  - service: "Forum"
    link: "forum.example.com"

supportLinks:
  documentation: "/docs" # recommended
  examples: "/examples"
  troubleshooting: "/docs/troubleshooting.md" # recommended

readme:
  usageExample: |
    Some example ```go run cli```
  # recommended

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/dear-github/dear-github/labels/starter%20issue" # replace dear-github with your actual url

emails:
  commercialSupport: "payed-support@example.com"
  security: "security@example.com" # required
  coc: "coc@example.com" # required

copyright:
  owner: "The Example Project authors" # default is project.name
  year: "2017" # required

cla:
  copyrightHolder: "Tiny Gopher" # required

maintainers:
  - name: "Huge Gopher"
    nick: "hugeGopher"
  - name: "Tiny Gopher"
    nick: "tinyGopher"

repo:
  link: "https://github.com/dear-github/dear-github/" # required
  type: "Github" # required

badges:
  - image: "https://img.shields.io/badge/state-unstable-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/dear-github/dear-github.svg"
    link: "https://github.com/dear-github/dear-github/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/dear-github/dear-github.svg"
    link: "LICENSE"
    alt: "license"
